CLASS z_class_demo DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z_class_demo IMPLEMENTATION.
METHOD IF_OO_ADT_CLASSRUN~MAIN.
OUT->WRITE('Hello World' ).
ENDMETHOD.
ENDCLASS.
